project:
  type: website
  output-dir: docs

website:
  title: "Texas Walkability Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Analysis

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    theme: cosmo
    highlight-style: github